App/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("weatherApp.urls")),
    path('admin/', admin.site.urls),
]

weatherApp/urls.py
from django.urls import path
from . import views


app_name = "weather"
urlpatterns = [
   path("", views.index, name="index"),
]

weatherApp/models.py
from django.db import models

# Create your models here.

weatherApp/views.py
from django.shortcuts import render
from django import forms
import requests
# Create your views here.


class cityNameForm(forms.Form):
   cityName = forms.CharField(label="", min_length=5, widget=forms.TextInput(attrs={'placeholder': 'eg: "London" '}))

def fetchData(cityName):
   try:
      #If you read this don't steal my API key hahahah
      response = requests.get(f"https://api.weatherapi.com/v1/forecast.json?key=d544248570e94c51a67211516211806&q={cityName}&days=3&aqi=yes&alerts=yes")

      if response.status_code != 400:
         return response.json()

      return False

   except Exception as e:
      return False

def index(request):
   if request.method == "POST":
      form = cityNameForm(request.POST)
      
      if form.is_valid():
         data = form.cleaned_data["cityName"]
         
         response = fetchData(data)
         
         if response != False:

            return render(request, "weatherApp/index.html", {
               #Current weather info
               "form": cityNameForm(),
               "city": response['location']['name'],
               "country": response['location']['country'],
               "condition": response['current']['condition']['text'],
               "conditionICO": response['current']['condition']['icon'],
               "temp_celsius": int(response['current']['temp_c']),
               "humidity": response['current']['humidity'],
               "wind_kph": response['current']['wind_kph'],
               "cloud": response['current']['cloud'],
               "UV": response['current']['uv'],
               "maxtemp_celsius": response['forecast']['forecastday'][0]['day']['maxtemp_c'],
               "mintemp_celsius": response['forecast']['forecastday'][0]['day']['mintemp_c'],
               "chance_of_rain": response['forecast']['forecastday'][0]['day']['daily_chance_of_rain'],
               "is_day": response['current']['is_day'],
               "last_updated": response['location']['localtime'],
               "pressure": response['current']['pressure_mb'],
               "wind_dir": response['current']['wind_dir'],

               "alerts": response['alerts']['alert'],
               "alerts_len": len(response['alerts']['alert']),

               #Forecast for tomorrow#
               "date": response['forecast']['forecastday'][1]['date'],
               "max_temp_t": response['forecast']['forecastday'][1]['day']['maxtemp_c'],
               "min_temp_t": response['forecast']['forecastday'][1]['day']['mintemp_c'],
               "chance_of_rain_t": response['forecast']['forecastday'][1]['day']['daily_chance_of_rain'],
               "condition_t": response['forecast']['forecastday'][1]['day']['condition']['text'],
               "condition_t_ICO": response['forecast']['forecastday'][1]['day']['condition']['icon'],
               "UV_t": response['forecast']['forecastday'][1]['day']['uv'],
               "sunrise_t": response['forecast']['forecastday'][1]['astro']['sunrise'],
               "sunset_t": response['forecast']['forecastday'][1]['astro']['sunset'],
               "moonrise_t": response['forecast']['forecastday'][1]['astro']['moonrise'],
               "moonset_t": response['forecast']['forecastday'][1]['astro']['moonset'],
               "moon_phase_t": response['forecast']['forecastday'][1]['astro']['moon_phase'],
               "max_wind": response['forecast']['forecastday'][1]['day']['maxwind_kph'],
               "avg_visibility_t": response['forecast']['forecastday'][1]['day']['avgvis_km'],
               "avg_humidity_t": response['forecast']['forecastday'][1]['day']['avghumidity']
            })

         else:
            return render(request, 'weatherApp/layout.html', {
               'form': form,
               'error': 'Something went wrong, try again.'
            })


   return render(request, "weatherApp/layout.html", {
            "form": cityNameForm()
         }) 


weatherApp/templates/weatherApp/index.html
{% extends "weatherApp/layout.html" %}

{% block data %}

   <section class="data">
      <div id="cityName">
         <h3>Weather today in: <span>{{ city }}/{{ country }}</span></h3>
      </div>
      <div id="cityData">
         <!--CURRENT WEATHER INFO-->
         <h5>Weather <span id="weather"><img src={{ conditionICO }} alt="{{ condition }}"> {{ condition }} </span></h5>
         <h5>Pressure <span>{{ pressure }}mb</span></h5>

         {% if temp_celsius >= 28 and temp_celsius < 50 %}
            <h5>Temperature <span><i class="fa-solid fa-temperature-high" style="color: #650d1c;"></i>{{ temp_celsius }}°C</span></h5>
         {% elif temp_celsius >= 10 and temp_celsius < 28 %}
            <h5>Temperature <span><i class="fa-solid fa-temperature-three-quarters" style="color: #ca2a42;"></i>{{ temp_celsius }}°C</span></h5>
         {% elif temp_celsius > 0 and temp_celsius < 10 %}
            <h5>Temperature <span><i class="fa-solid fa-temperature-quarter" style="color: #d76272;"></i>{{ temp_celsius }}°C</span></h5>
         {% elif temp_celsius <= 0 %}
            <h5>Temperature <span><i class="fa-solid fa-temperature-low" style="color: #3da8e3;"></i>{{ temp_celsius }}°C</span></h5>
         {% endif %}
         
         <h5>Humidity <span><i class="fa-solid fa-droplet fa-bounce" style=" --fa-bounce-start-scale-x: 1; --fa-bounce-start-scale-y: 1; --fa-bounce-jump-scale-x: 1; --fa-bounce-jump-scale-y: 1; --fa-bounce-land-scale-x: 1; --fa-bounce-land-scale-y: 1; --fa-bounce-rebound: 0; color: #25ced1;"></i>{{ humidity }}% </span></h5>
         

         <!--Rotate the arrow to the side of wind_dir-->
         {% if wind_dir == 'N' %}
            <h5>Wind <span><i class="fa-solid fa-wind" style="color: #297f90"></i>{{ wind_kph }} km/h <i class="fa-solid fa-arrow-down-long" style="transform: rotate(0deg);"></i>{{wind_dir}}</span></h5>
         {% elif wind_dir == 'NE' %}
            <h5>Wind <span><i class="fa-solid fa-wind" style="color: #297f90"></i>{{ wind_kph }} km/h <i class="fa-solid fa-arrow-down-long" style="transform: rotate(45deg);"></i>{{wind_dir}}</span></h5>
         {% elif wind_dir == 'NW' %}
            <h5>Wind <span><i class="fa-solid fa-wind" style="color: #297f90"></i>{{ wind_kph }} km/h <i class="fa-solid fa-arrow-down-long" style="transform: rotate(317deg);"></i>{{wind_dir}}</span></h5>
         {% elif wind_dir == 'E' %}
            <h5>Wind <span><i class="fa-solid fa-wind" style="color: #297f90"></i>{{ wind_kph }} km/h <i class="fa-solid fa-arrow-down-long" style="transform: rotate(90deg);"></i>{{wind_dir}}</span></h5>
         {% elif wind_dir == 'W' %}
            <h5>Wind <span><i class="fa-solid fa-wind" style="color: #297f90"></i>{{ wind_kph }} km/h <i class="fa-solid fa-arrow-down-long" style="transform: rotate(270deg);"></i>{{wind_dir}}</span></h5>
         {% elif wind_dir == 'S' %}
            <h5>Wind <span><i class="fa-solid fa-wind" style="color: #297f90"></i>{{ wind_kph }} km/h <i class="fa-solid fa-arrow-down-long" style="transform: rotate(180deg);"></i>{{wind_dir}}</span></h5>
         {% elif wind_dir == 'SE' %}
            <h5>Wind <span><i class="fa-solid fa-wind" style="color: #297f90"></i>{{ wind_kph }} km/h <i class="fa-solid fa-arrow-down-long" style="transform: rotate(135deg);"></i>{{wind_dir}}</span></h5>
         {% elif wind_dir == 'SW' %}
            <h5>Wind <span><i class="fa-solid fa-wind" style="color: #297f90"></i>{{ wind_kph }} km/h <i class="fa-solid fa-arrow-down-long" style="transform: rotate(225deg);"></i>{{wind_dir}}</span></h5>
         {% elif wind_dir == 'ESE' %}
            <h5>Wind <span><i class="fa-solid fa-wind" style="color: #297f90"></i>{{ wind_kph }} km/h <i class="fa-solid fa-arrow-down-long" style="transform: rotate(115deg);"></i>{{wind_dir}}</span></h5>
         {% elif wind_dir == 'SSE' %}
            <h5>Wind <span><i class="fa-solid fa-wind" style="color: #297f90"></i>{{ wind_kph }} km/h <i class="fa-solid fa-arrow-down-long" style="transform: rotate(156deg);"></i>{{wind_dir}}</span></h5>
         {% elif wind_dir == 'SSW' %}
            <h5>Wind <span><i class="fa-solid fa-wind" style="color: #297f90"></i>{{ wind_kph }} km/h <i class="fa-solid fa-arrow-down-long" style="transform: rotate(205deg);"></i>{{wind_dir}}</span></h5>
         {% elif wind_dir == 'WSW' %}
            <h5>Wind <span><i class="fa-solid fa-wind" style="color: #297f90"></i>{{ wind_kph }} km/h <i class="fa-solid fa-arrow-down-long" style="transform: rotate(245deg);"></i>{{wind_dir}}</span></h5>
         {% elif wind_dir == 'WNW' %}
            <h5>Wind <span><i class="fa-solid fa-wind" style="color: #297f90"></i>{{ wind_kph }} km/h <i class="fa-solid fa-arrow-down-long" style="transform: rotate(340deg);"></i>{{wind_dir}}</span></h5>
         {% elif wind_dir == 'NNW' %}
            <h5>Wind <span><i class="fa-solid fa-wind" style="color: #297f90"></i>{{ wind_kph }} km/h <i class="fa-solid fa-arrow-down-long" style="transform: rotate(295deg);"></i>{{wind_dir}}</span></h5>
         {% elif wind_dir == 'NNE' %}
            <h5>Wind <span><i class="fa-solid fa-wind" style="color: #297f90"></i>{{ wind_kph }} km/h <i class="fa-solid fa-arrow-down-long" style="transform: rotate(20deg);"></i>{{wind_dir}}</span></h5>
         {% elif wind_dir == 'ENE' %}
            <h5>Wind <span><i class="fa-solid fa-wind" style="color: #297f90"></i>{{ wind_kph }} km/h <i class="fa-solid fa-arrow-down-long" style="transform: rotate(70deg);"></i>{{wind_dir}}</span></h5>
         {% endif %}

         <!--If cloud is 1 then there are clouds, else clear sky.-->
         {% if cloud == 1 %}
            <h5>Clouds <span><i class="fa-solid fa-cloud" style="color: #25ced1;"></i>Cloudy</span></h5>
         {% else %}
            <h5>Clouds <span><i class="fa-solid fa-sun fa-spin" style="color: #ffee32;"></i>Clear sky</span></h5> 
         {% endif %}
            

         <!--Check the UV-->
         {% if UV >= 3 and UV <= 5 %}
            <h5>UV <span>{{ UV }}</span></h5>
         {% elif UV >= 6 and UV <= 7 %}
            <h5>UV <span><i class="fa-solid fa-circle-info fa-beat-fade" style="color: #ffba08;"></i>{{ UV }}</span></h5>
         {% elif UV >= 8 and UV <= 10 %}
            <h5>UV <span><i class="fa-solid fa-triangle-exclamation fa-fade" style="color: #824b03;"></i> {{ UV }}</span></h5>
         {% elif UV > 11  %}
            <h5>UV <span><i class="fa-solid fa-skull-crossbones fa-fade" style="color: #dc2f02;"></i>{{ UV }}</span></h5>   
         {% else %}
            <h5>UV <span>{{ UV }}</span></h5>
         {% endif %}

         <h5>Max temperature <span>{{ maxtemp_celsius }}°C</span></h5>
         <h5>Min temperature <span>{{ mintemp_celsius }}°C</span></h5>

         {% if chance_of_rain > 50 %}
            <h5>Chances of rain <span><i class="fa-solid fa-cloud-showers-water" style="color: #25ced1;"></i>{{ chance_of_rain }}%</span></h5>
         {% elif chance_of_rain >= 30 and chance_of_rain <= 50 %}
            <h5>Chances of rain <span><i class="fa-solid fa-umbrella" style="color: #43aa8b;"></i>{{ chance_of_rain }}%</span></h5>
         {% else %}
            <h5>Chances of rain <span>{{ chance_of_rain }}%</span></h5>
         {% endif %}

         {% if is_day == 0%}
            <h5>Day/Night <span><i class="fa-solid fa-moon" style="color: #333533;"></i> Night</span></h5> <!--If 0 then no-->
         {% else %}
            <h5>Day/Night <span><i class="fa-solid fa-sun fa-spin" style="color: #ffee32;"></i> Day</span></h5>
         {% endif %}
         
         <h5>Last updated <span>{{ last_updated }}</span></h5>

      </div>



      <!--WEATHER FOR TOMORROW-->
      <div id="cityName">
         <h3>Weather tomorrow in: <span>{{ city }}/{{ country }}</span></h3>
      </div>
      <div id="tomorrowWeather">
         <h5>Weather <span id="weather"><img src={{ condition_t_ICO }} alt="{{ condition_t }}"> {{ condition_t }} </span></h5>
         <h5>Max temperature <span>{{ max_temp_t }}°C</span></h5>
         <h5>Min temperature <span>{{ min_temp_t }}°C</span></h5>
         
         {% if chance_of_rain_t > 50 %}
            <h5>Chances of rain <span><i class="fa-solid fa-cloud-showers-water" style="color: #25ced1;"></i>{{ chance_of_rain_t }}%</span></h5>
         {% elif chance_of_rain_t >= 30 and chance_of_rain_t <= 50 %}
            <h5>Chances of rain <span><i class="fa-solid fa-umbrella" style="color: #43aa8b;"></i>{{ chance_of_rain_t }}%</span></h5>
         {% else %}
            <h5>Chances of rain <span>{{ chance_of_rain_t }}%</span></h5>
         {% endif %}
         
         <h5>Max Wind <span><i class="fa-solid fa-wind" style="color: #297f90"></i>{{ max_wind }} km/h</span></h5>
         <h5>Average visibility <span>{{avg_visibility_t}}km</span></h5>

         {% if UV_t >= 3 and UV_t <= 5 %}
            <h5>UV <span>{{ UV }}</span></h5>
         {% elif UV_t >= 6 and UV_t <= 7 %}
            <h5>UV <span><i class="fa-solid fa-circle-info fa-beat-fade" style="color: #ffba08;"></i>{{ UV_t }}</span></h5>
         {% elif UV_t >= 8 and UV_t <= 10 %}
            <h5>UV <span><i class="fa-solid fa-triangle-exclamation fa-fade" style="color: #824b03;"></i> {{ UV_t }}</span></h5>
         {% elif UV_t >= 11  %}
            <h5>UV <span><i class="fa-solid fa-skull-crossbones fa-fade" style="color: #dc2f02;"></i>{{ UV_t }}</span></h5>   
         {% else %}
            <h5>UV <span>{{ UV_t }}</span></h5>
         {% endif %}

         <h5>Average humidity <span><i class="fa-solid fa-droplet fa-bounce" style=" --fa-bounce-start-scale-x: 1; --fa-bounce-start-scale-y: 1; --fa-bounce-jump-scale-x: 1; --fa-bounce-jump-scale-y: 1; --fa-bounce-land-scale-x: 1; --fa-bounce-land-scale-y: 1; --fa-bounce-rebound: 0; color: #25ced1;"></i>{{avg_humidity_t}}%</span></h5>

         <h5>Sunrise/Sunset <span>{{sunrise_t}} / {{sunset_t}}</span></h5>
         <h5>Moonrise/Moonset <span>{{moonrise_t}} / {{moonset_t}}</span></h5>
         <h5>Moon phase <span>{{moon_phase_t}}</span></h5>
         <h5>Date <span>{{date}}</span></h5>

      </div>

   </section>

{% endblock %}

weatherApp/templates/weatherApp/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <script src="https://kit.fontawesome.com/e8303bef12.js" crossorigin="anonymous"></script>
      <title>Weather App</title>
      <link rel="shortcut icon" href="{% static 'weatherApp/images/favicon.svg' %}" type="image/x-icon">
      <link rel="stylesheet" href="{% static 'weatherApp/styles/style.css' %}">
      <script defer src="{% static 'weatherApp/script/app.js' %}"></script>
   </head>
   <body>
      <section class="main">
         <!--form div-->
         <div id="form">
            <h1 for="">Write city name: </h1>
            <form action="{% url 'weather:index' %}" method="post">
               {% csrf_token %}
               {{ form }}
               <br>
               <button type="submit">Get</button>
            </form>

            <!--Errors div-->
            <div id="error">
               <h3>{{ error }}</h6>
            </div>
         </div>

         <!--Image div-->
         <div id="image">
            <img src="{% static 'weatherApp/images/logo.svg' %}">
         </div>

      </section>

      <!--Data section -->
      
      {% block data %}
      
      {% endblock %}

      <footer class="footer">
         <div id="links">
            <ul>
               <li><a href="https://github.com/AntonioNDev" target="_blank" rel="noopener noreferrer"><i class="fa-brands fa-github"></i>GitHub</a></li>
               <li><a href="https://www.linkedin.com/in/antonio-n-12362b209/" target="_blank" rel="noopener noreferrer">Linked<i class="fa-brands fa-linkedin"></i></a></li>
               <li><a href="https://www.weatherapi.com/" target="_blank" rel="noopener noreferrer">API</a></li>
            </ul>
            <span id="credits">© AntonioNDev. All rights reserved.</span>
         </div>
      </footer>
   </body>
</html>